# Generated by Django 3.2.9 on 2023-09-07 10:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0007_auto_20230830_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', to='service.Product', verbose_name='Выберите товар/услугу для акций и скидки'),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='service.product', verbose_name='Товар/Услуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг продукта',
                'verbose_name_plural': 'Рейтинг продуктов',
            },
        ),
    ]
