# Generated by Django 3.2.9 on 2023-09-07 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20230907_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
